<a href="https://colab.research.google.com/github/idouba/pytorch/blob/main/%E2%80%9CLinear_Regression_in_Pytorch_ipynb%E2%80%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imports

In [ ]:
# @title
import torch
import numpy as np

## Data

In [ ]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])


In [ ]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


## Dataset

In [ ]:
from torch.utils.data import TensorDataset

dataset = TensorDataset(inputs, targets)

In [ ]:
dataset[:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

## DataLoader

In [ ]:
from torch.utils.data import DataLoader

batch_size = 3
train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [ ]:
# A Batch Sample
for inp,target in train_loader:
    print(inp)
    print(target)
    break

tensor([[ 68.,  96.,  71.],
        [103.,  43.,  36.],
        [ 73.,  67.,  43.]])
tensor([[104., 118.],
        [ 20.,  38.],
        [ 56.,  70.]])


## Linear Regression

In [ ]:
w = torch.randn(2, 3, requires_grad=True) #Weights
b = torch.randn(2, requires_grad=True) # Bias
print(w)
print(b)

tensor([[-0.2510,  0.4051, -0.7637],
        [-0.5891, -0.8131,  1.0250]], requires_grad=True)
tensor([-1.7385,  0.1349], requires_grad=True)


In [ ]:
# Text classidication, lm etc
def model(X):
    return X @ w.t() + b

In [ ]:
for x,y in train_loader:
    preds = model(x)
    print("Prediction is :\n",preds)
    print("\nActual targets is :\n",y)
    break

Prediction is :
 tensor([[ -38.9811,  -57.5879],
        [ -13.5930, -100.6212],
        [ -33.6310,  -46.8192]], grad_fn=<AddBackward0>)

Actual targets is :
 tensor([[ 80., 102.],
        [119., 133.],
        [103., 119.]])


### Loss

In [ ]:
def mse_loss(predictions, targets):
    difference = predictions - targets
    return torch.sum(difference * difference) / difference.numel()

# Mean: sum/count

In [ ]:
for x,y in train_loader:
    preds = model(x)
    print("Prediction is :\n",preds)
    print("\nActual targets is :\n",y)
    print("\nLoss is: ",mse_loss(preds, y))
    break

Prediction is :
 tensor([[-26.4190, -53.0486],
        [-37.5266, -57.2181],
        [-37.8124, -59.4260]], grad_fn=<AddBackward0>)

Actual targets is :
 tensor([[ 57.,  69.],
        [ 21.,  38.],
        [ 81., 101.]])

Loss is:  tensor(12366.5557, grad_fn=<DivBackward0>)


In [ ]:
epochs = 50
for i in range(epochs):
    # Iterate through training dataloader
    for x,y in train_loader:
        # Generate Prediction
        preds = model(x)
        # Get the loss and perform backpropagation
        loss = mse_loss(preds, y)
        loss.backward()
        # print(loss)
        # Let's update the weights
        with torch.no_grad():
            w -= w.grad * 1e-5 # w = w - w.grad * 0.00001
            b -= b.grad * 1e-5
            # Set the gradients to zero
            w.grad.zero_()
            b.grad.zero_()
    print(f"Epoch {i}/{epochs}: Loss: {loss}")

Epoch 0/50: Loss: 3818.1455078125
Epoch 1/50: Loss: 648.2687377929688
Epoch 2/50: Loss: 395.8610534667969
Epoch 3/50: Loss: 537.2958374023438
Epoch 4/50: Loss: 195.60899353027344
Epoch 5/50: Loss: 338.1976318359375
Epoch 6/50: Loss: 361.8482666015625
Epoch 7/50: Loss: 294.2668762207031
Epoch 8/50: Loss: 315.0870666503906
Epoch 9/50: Loss: 362.9952697753906
Epoch 10/50: Loss: 137.4292755126953
Epoch 11/50: Loss: 426.2330017089844
Epoch 12/50: Loss: 130.20574951171875
Epoch 13/50: Loss: 171.3480987548828
Epoch 14/50: Loss: 329.6540222167969
Epoch 15/50: Loss: 226.9811248779297
Epoch 16/50: Loss: 239.72654724121094
Epoch 17/50: Loss: 216.0075225830078
Epoch 18/50: Loss: 102.84173583984375
Epoch 19/50: Loss: 177.7810516357422
Epoch 20/50: Loss: 128.1374053955078
Epoch 21/50: Loss: 208.1404571533203
Epoch 22/50: Loss: 233.2897491455078
Epoch 23/50: Loss: 87.17069244384766
Epoch 24/50: Loss: 157.66944885253906
Epoch 25/50: Loss: 105.62777709960938
Epoch 26/50: Loss: 243.7537384033203
Epoch 2

## Results

In [ ]:
for x,y in train_loader:
    preds = model(x)
    print("Prediction is :\n",preds)
    print("\nActual targets is :\n",y)
    break

Prediction is :
 tensor([[ 74.2564, 105.0351],
        [128.2444, 120.6179],
        [ 86.1022, 126.3696]], grad_fn=<AddBackward0>)

Actual targets is :
 tensor([[ 82., 100.],
        [119., 133.],
        [104., 118.]])
